name: pokemon
description: Get a random name from Pokémon creatures.
version: 0.0.1
repository: https://github.com/javoeria/randomify/tree/main/packages/pokemon

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - pokemon
  - random
